version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=myflaskdbserver.mysql.database.azure.com  # Azure MySQL server
      - MYSQL_USER=mysqladmin
      - MYSQL_PASSWORD=Paul*1928
      - MYSQL_DATABASE=log_monitoring
      - FLASK_ENV=development
    volumes:
      - ./app:/app/app
      - /home/madagalapaul/log_monitoring/logs/nginx_json_logs.txt:/app/app/nginx_json_logs.txt  
    restart: always
    networks:
      - monitoring_network

volumes:
  # No need for db_data volume since there's no local MySQL container
    db_data:

networks:
  monitoring_network:  
    driver: bridge
