version: '3.8'

services:
  web:
    build:
      context: ./app  
      dockerfile: Dockerfile  
    ports:
      - "5000:5000"
    environment:
      DATABASE_HOST: db
      DATABASE_USER: root
      DATABASE_PASSWORD: Paul*1928
      DATABASE_DB: sample_crud_db
    depends_on:
      db:
        condition: service_healthy  # Wait for MySQL to be healthy
    networks:
      - mynetwork

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Paul*1928
      MYSQL_DATABASE: sample_crud_db
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:

networks:
  mynetwork:
