name: CI/CD Workflow for Flask App with Docker and ACR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Log in to Azure Container Registry
      - name: Log in to Azure Container Registry
        run: |
          az login --service-principal \
            --username ${{ secrets.ACR_USERNAME }} \
            --password ${{ secrets.ACR_PASSWORD }} \
            --tenant ${{ secrets.AZURE_TENANT_ID }}
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          az acr login --name myregistry123456

      # Step 3: Build and push the Docker image to ACR
      - name: Build and push Docker image
        run: |
          docker build -t myregistry123456.azurecr.io/dockerapp:latest ./log_monitoring
          docker push myregistry123456.azurecr.io/dockerapp:latest

      # Step 4: Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: dockerapp  # Replace with your Azure App Service name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'myregistry123456.azurecr.io/dockerapp:latest'
