name: CI/CD Workflow for Flask App with Docker and ACR

on:
  push:
    branches:
      - main  # Workflow runs on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Run the job on Ubuntu

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Log in to Azure Container Registry
      - name: Log in to Azure Container Registry
        run: |
          az login --service-principal \
            --username 3abf43ca-1a97-494f-acef-8fc5fd97f677 \
            --password RzN8Q~WQXff7bGyvIEzSNWYH6mRVCpLNS3MwQcSg \
            --tenant d7d7efd6-955f-4294-8526-b638e0bc351b
          az acr login --name myregistry123456

      # Step 3: Build and push the Docker image to ACR
      - name: Build and push Docker image
        run: |
          docker build -t myregistry123456.azurecr.io/dockerapp:latest .  # Build Docker image
          docker push myregistry123456.azurecr.io/dockerapp:latest        # Push to ACR

      # Step 4: Deploy to Azure Web App
      - name: Azure Web App Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: dockerapp  # Replace with your Azure App Service name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Add Azure Publish Profile as a secret
