# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - dockerapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://myregistry123456.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_40efd69b58dd42a992d9b305d63fe682 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_63de6125e1f54c0f8d6d92b03fccb31b }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: myregistry123456.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_40efd69b58dd42a992d9b305d63fe682 }}/myregistry123456.azurecr.io/dockerapp:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'dockerapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_343d9f60d74f4472af600be65ce15c29 }}
        images: 'myregistry123456.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_40efd69b58dd42a992d9b305d63fe682 }}/myregistry123456.azurecr.io/dockerapp:${{ github.sha }}'